print("Welcome to emobilis mobile technology")
print(".....................................")
print("We train programmers")
print("Introduction to python programming language")
print("Python is the most porpular programming language")
print("******", 2*2)
print("*    *", 4*4)
print("******", 6*6)
print("*    *", 8*8)
print("******", 10*10)
print(999999*99999999999)
